# Generated by Django 4.2 on 2026-05-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_customer_name_sale_payment_method_saleitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
