# Generated by Django 4.2 on 2026-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_delete_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
