# Generated by Django 4.2 on 2026-03-22 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit.creditsale'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
