# Generated by Django 4.2 on 2026-05-22 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0003_customer_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_sales_issued', to=settings.AUTH_USER_MODEL),
        ),
    ]
