# Generated by Django 4.2 on 2026-05-23 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_medicine_price_medicine_barcode_and_more'),
        ('credit', '0004_alter_customer_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditsale',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='CreditSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='credit.creditsale')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
            ],
            options={
                'db_table': 'credit_sale_items',
            },
        ),
    ]
