# Generated by Django 4.2 on 2026-03-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=15)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_license', models.CharField(blank=True, max_length=100)),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('diagnosis', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_quantity', models.IntegerField()),
                ('filled_quantity', models.IntegerField(default=0)),
                ('dosage_instructions', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
    ]
