# Generated by Django 6.0.7 on 2026-08-03 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_medicine_price_medicine_barcode_and_more'),
        ('stock', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('expired', 'Expired'), ('write_off', 'Write Off'), ('stock_take', 'Stock Take')], max_length=20)),
                ('quantity_changed', models.IntegerField(help_text='Positive for increase, negative for decrease')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Quantity changed × unit cost', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Reference like sale ID, purchase order, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='medicines.medicine')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='inventory_h_created_c65f00_idx'), models.Index(fields=['medicine'], name='inventory_h_medicin_d06ec7_idx'), models.Index(fields=['action_type'], name='inventory_h_action__a3febf_idx')],
            },
        ),
    ]
