# Generated by Django 4.2 on 2026-03-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, help_text='QR/Bar code for scanning', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default discount %', max_digits=5),
        ),
        migrations.AddField(
            model_name='medicine',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Retail selling price', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('strip', 'Strip'), ('box', 'Box'), ('pack', 'Pack'), ('ml', 'Milliliter'), ('g', 'Gram')], default='tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_per_pack',
            field=models.IntegerField(default=1, help_text='Number of units per pack/strip/bottle'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wholesale selling price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
